name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # or the branch you want to trigger the action

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no abdo@192.168.3.7 "cd /var/www/test-deploy && git pull"
